import time
import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.live import Live
from rich.status import Status

# Initialize Typer app and Rich console
app = typer.Typer(help="Title 8 Cal/OSHA Compliance Agent CLI")
console = Console()

def show_welcome_banner():
    """Renders a clean, high-contrast structural header."""
    banner_text = Text()
    banner_text.append("CALIFORNIA TITLE 8 COMPLIANCE AGENT\n", style="bold white")
    banner_text.append("Automated Cal/OSHA Regulation & Citation Matcher", style="dim white")
    
    console.print(
        Panel(
            banner_text,
            box=rich.box.ROUNDED,
            border_style="cyan",
            padding=(1, 2),
            expand=False
        )
    )

def render_compliance_results(query: str, citations: list[dict]):
    """Renders vector search results in an elegant, readable structure."""
    console.print(f"\n[bold cyan] Analysis for query:[/bold cyan] '[white]{query}[/white]'\n")
    
    # Create a table for the regulations found
    table = Table(title="Applicable Title 8 Regulations", box=rich.box.SIMPLE_HEAD)
    table.add_column("Citation", style="bold green", no_wrap=True)
    table.add_column("Section Title", style="bold white")
    table.add_column("Subchapter / Scope", style="dim")
    
    for c in citations:
        table.add_row(c["citation"], c["section_title"], c["subchapter_name"])
        
    console.print(table)
    console.print("\n" + "─" * 60 + "\n")

    # Render detailed content panels
    for i, c in enumerate(citations, 1):
        content = Text()
        content.append(f"Breadcrumb: {c['breadcrumb_path']}\n", style="dim")
        content.append(f"Source URL: {c['source_url']}\n\n", style="dim underline blue")
        content.append(c["text"], style="white")
        
        console.print(
            Panel(
                content,
                title=f"[bold green][{i}] {c['citation']} ── {c['section_title']}[/bold green]",
                title_align="left",
                border_style="gray37",
                padding=(1, 2)
            )
        )
        console.print()

@app.command()
def ask(
    query: str = typer.Argument(..., help="The facility type or practice to audit (e.g., 'restaurant', 'farm')"),
    limit: int = typer.Option(3, "--limit", "-l", help="Number of results to return")
):
    """
    Query the Title 8 compliance agent for applicable regulations.
    """
    show_welcome_banner()
    
    # Elegant loading spinner while your database/Gemini does vector search
    with Status("[bold yellow]Scanning Title 8 vector space via Supabase...", console=console, spinner="dots"):
        # Simulate database retrieval delay — replace this with your actual agent/rag call
        time.sleep(2) 
        
        # Mocking the data structure coming back from your database matching your exact extraction schema
        mock_results = [
            {
                "citation": "8 CCR § 3203",
                "section_title": "Injury and Illness Prevention Program.",
                "subchapter_name": "General Industry Safety Orders",
                "breadcrumb_path": "Title 8 -> Division 1 -> Chapter 4 -> Subchapter 7 -> §3203",
                "source_url": "https://dir.ca.gov/title8/3203.html",
                "text": "(a) Every employer shall establish, implement and maintain an effective Injury and Illness Prevention Program (IIPP). The Program shall be in writing and, shall, at a minimum, identify the person or persons with authority and responsibility for implementing the Program..."
            },
            {
                "citation": "8 CCR § 3364",
                "section_title": "Sanitary Facilities.",
                "subchapter_name": "General Industry Safety Orders",
                "breadcrumb_path": "Title 8 -> Division 1 -> Chapter 4 -> Subchapter 7 -> §3364",
                "source_url": "https://dir.ca.gov/title8/3364.html",
                "text": "(a) Water closets shall be provided for each sex according to the following table. Where toilet rooms will be occupied by only one person at a time, can be locked from the inside, and contain at least one water closet, separate toilet rooms for each sex need not be provided..."
            }
        ][:limit]

    # Present the findings beautifully
    render_compliance_results(query, mock_results)
    
    # Legal Disclaimer block requested by the prompt criteria
    console.print(
        Panel(
            "[bold red]DISCLAIMER:[/bold red] [dim white]This output is generated by an AI assistant trained on Cal/OSHA Title 8 data. It does not constitute official legal advice. Always verify with official DIR resources or counsel.[/dim white]",
            border_style="red",
            box=rich.box.SQUARE
        )
    )

if __name__ == "__main__":
    import rich.box # Import required box styles safely
    app()